name: Add Emojis to Commits

on:
  push:
    branches:
      - main

jobs:
  add-emojis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add emoji to commit message
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "GitHub Actions"
          git commit --amend -m "$(git log -1 --pretty=%B) 🎉"
          git push --force
